/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 4.24.3
 * source: proto/eventsub.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
 import * as pb_1 from "google-protobuf";
 import * as grpc_1 from "@grpc/grpc-js";
 export class SendEventRequest extends pb_1.Message {
     #one_of_decls: number[][] = [];
     constructor(data?: any[] | {
         type?: string;
         event?: string;
     }) {
         super();
         pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
         if (!Array.isArray(data) && typeof data == "object") {
             if ("type" in data && data.type != undefined) {
                 this.type = data.type;
             }
             if ("event" in data && data.event != undefined) {
                 this.event = data.event;
             }
         }
     }
     get type() {
         return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
     }
     set type(value: string) {
         pb_1.Message.setField(this, 1, value);
     }
     get event() {
         return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
     }
     set event(value: string) {
         pb_1.Message.setField(this, 2, value);
     }
     static fromObject(data: {
         type?: string;
         event?: string;
     }): SendEventRequest {
         const message = new SendEventRequest({});
         if (data.type != null) {
             message.type = data.type;
         }
         if (data.event != null) {
             message.event = data.event;
         }
         return message;
     }
     toObject() {
         const data: {
             type?: string;
             event?: string;
         } = {};
         if (this.type != null) {
             data.type = this.type;
         }
         if (this.event != null) {
             data.event = this.event;
         }
         return data;
     }
     serialize(): Uint8Array;
     serialize(w: pb_1.BinaryWriter): void;
     serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
         const writer = w || new pb_1.BinaryWriter();
         if (this.type.length)
             writer.writeString(1, this.type);
         if (this.event.length)
             writer.writeString(2, this.event);
         if (!w)
             return writer.getResultBuffer();
     }
     static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SendEventRequest {
         const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SendEventRequest();
         while (reader.nextField()) {
             if (reader.isEndGroup())
                 break;
             switch (reader.getFieldNumber()) {
                 case 1:
                     message.type = reader.readString();
                     break;
                 case 2:
                     message.event = reader.readString();
                     break;
                 default: reader.skipField();
             }
         }
         return message;
     }
     serializeBinary(): Uint8Array {
         return this.serialize();
     }
     static deserializeBinary(bytes: Uint8Array): SendEventRequest {
         return SendEventRequest.deserialize(bytes);
     }
 }
 export class SendEventResponse extends pb_1.Message {
     #one_of_decls: number[][] = [];
     constructor(data?: any[] | {
         status?: number;
         message?: string;
     }) {
         super();
         pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
         if (!Array.isArray(data) && typeof data == "object") {
             if ("status" in data && data.status != undefined) {
                 this.status = data.status;
             }
             if ("message" in data && data.message != undefined) {
                 this.message = data.message;
             }
         }
     }
     get status() {
         return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
     }
     set status(value: number) {
         pb_1.Message.setField(this, 1, value);
     }
     get message() {
         return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
     }
     set message(value: string) {
         pb_1.Message.setField(this, 2, value);
     }
     static fromObject(data: {
         status?: number;
         message?: string;
     }): SendEventResponse {
         const message = new SendEventResponse({});
         if (data.status != null) {
             message.status = data.status;
         }
         if (data.message != null) {
             message.message = data.message;
         }
         return message;
     }
     toObject() {
         const data: {
             status?: number;
             message?: string;
         } = {};
         if (this.status != null) {
             data.status = this.status;
         }
         if (this.message != null) {
             data.message = this.message;
         }
         return data;
     }
     serialize(): Uint8Array;
     serialize(w: pb_1.BinaryWriter): void;
     serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
         const writer = w || new pb_1.BinaryWriter();
         if (this.status != 0)
             writer.writeUint32(1, this.status);
         if (this.message.length)
             writer.writeString(2, this.message);
         if (!w)
             return writer.getResultBuffer();
     }
     static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SendEventResponse {
         const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SendEventResponse();
         while (reader.nextField()) {
             if (reader.isEndGroup())
                 break;
             switch (reader.getFieldNumber()) {
                 case 1:
                     message.status = reader.readUint32();
                     break;
                 case 2:
                     message.message = reader.readString();
                     break;
                 default: reader.skipField();
             }
         }
         return message;
     }
     serializeBinary(): Uint8Array {
         return this.serialize();
     }
     static deserializeBinary(bytes: Uint8Array): SendEventResponse {
         return SendEventResponse.deserialize(bytes);
     }
 }
 interface GrpcUnaryServiceInterface<P, R> {
     (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
     (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
     (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
     (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
 }
 interface GrpcStreamServiceInterface<P, R> {
     (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
     (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
 }
 interface GrpWritableServiceInterface<P, R> {
     (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
     (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
     (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
     (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
 }
 interface GrpcChunkServiceInterface<P, R> {
     (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
     (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
 }
 interface GrpcPromiseServiceInterface<P, R> {
     (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
     (message: P, options?: grpc_1.CallOptions): Promise<R>;
 }
 export abstract class UnimplementedEventSubServiceService {
     static definition = {
         SendEvent: {
             path: "/EventSubService/SendEvent",
             requestStream: false,
             responseStream: false,
             requestSerialize: (message: SendEventRequest) => Buffer.from(message.serialize()),
             requestDeserialize: (bytes: Buffer) => SendEventRequest.deserialize(new Uint8Array(bytes)),
             responseSerialize: (message: SendEventResponse) => Buffer.from(message.serialize()),
             responseDeserialize: (bytes: Buffer) => SendEventResponse.deserialize(new Uint8Array(bytes))
         }
     };
     [method: string]: grpc_1.UntypedHandleCall;
     abstract SendEvent(call: grpc_1.ServerUnaryCall<SendEventRequest, SendEventResponse>, callback: grpc_1.sendUnaryData<SendEventResponse>): void;
 }
 export class EventSubServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedEventSubServiceService.definition, "EventSubService", {}) {
     constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
         super(address, credentials, options);
     }
     SendEvent: GrpcUnaryServiceInterface<SendEventRequest, SendEventResponse> = (message: SendEventRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<SendEventResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<SendEventResponse>, callback?: grpc_1.requestCallback<SendEventResponse>): grpc_1.ClientUnaryCall => {
         return super.SendEvent(message, metadata, options, callback);
     };
 }
 