apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamwizard-backend-eventsub
spec:
  replicas: 5
  selector:
    matchLabels:
      app: streamwizard-backend-eventsub
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled  # This annotation enables automatic injection
      labels:
        app: streamwizard-backend-eventsub
    spec:
      containers:
        - name: streamwizard-backend-eventsub
          image: ghcr.io/streamerbuddybot/eventsub:f84224ce85c2d6c9169cfa349550e8a677e22ba6
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: streamwizard-backend
          volumeMounts:
            - name: grpc-dns
              mountPath: /usr/src/app/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: grpc-dns
          configMap:
            name: grpc-dns
